'use client';

import { useState } from 'react';
import Sidebar from '@/components/sidebar';
import BookingManagement from '@/components/booking';

interface Booking {
  id: string;
  bookingId: string;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  photographerName: string;
  category: string;
  subcategory: string;
  packageType: string;
  packageName: string;
  bookingDate: string;
  eventDate: string;
  eventTime: string;
  location: string;
  duration: string;
  totalAmount: number;
  advanceAmount: number;
  remainingAmount: number;
  paymentStatus: 'paid' | 'pending' | 'partial';
  bookingStatus: 'confirmed' | 'pending' | 'cancelled' | 'completed';
  serviceStatus: 'today' | 'upcoming' | 'completed' | 'cancelled';
  deliveryStatus: 'pending' | 'delivered' | 'not_applicable';
  createdAt: string;
}

// Get today's date
const getTodayDate = () => {
  const today = new Date();
  return today.toISOString().split('T')[0];
};

// Get tomorrow's date
const getTomorrowDate = () => {
  const tomorrow = new Date();
  tomorrow.setDate(tomorrow.getDate() + 1);
  return tomorrow.toISOString().split('T')[0];
};

// Get current time
const getCurrentTime = () => {
  const now = new Date();
  return now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true });
};

// Sample initial bookings data with realistic tab distribution
const initialBookings: Booking[] = [
  // TODAY's Bookings - Most recent first
  {
    id: '1',
    bookingId: 'BK001',
    customerName: 'Rajesh Kumar',
    customerEmail: 'rajesh.kumar@example.com',
    customerPhone: '+91 98765 43210',
    photographerName: 'Arjun Singh',
    category: 'Wedding',
    subcategory: 'Traditional Wedding',
    packageType: 'Individual',
    packageName: 'Premium Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '10:00 AM',
    location: 'Mumbai, Maharashtra',
    duration: '8 Hours',
    totalAmount: 50000,
    advanceAmount: 15000,
    remainingAmount: 35000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: getCurrentTime()
  },
  {
    id: '2',
    bookingId: 'BK002',
    customerName: 'Priya Sharma',
    customerEmail: 'priya.sharma@example.com',
    customerPhone: '+91 98765 43211',
    photographerName: 'Vikram Patel',
    category: 'Pre-Wedding',
    subcategory: 'Outdoor Shoot',
    packageType: 'Fixed',
    packageName: 'Gold Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '6:00 AM',
    location: 'Goa',
    duration: '6 Hours',
    totalAmount: 35000,
    advanceAmount: 35000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '08:30 AM'
  },
  {
    id: '3',
    bookingId: 'BK003',
    customerName: 'Amit Verma',
    customerEmail: 'amit.verma@example.com',
    customerPhone: '+91 98765 43212',
    photographerName: 'Rahul Mehta',
    category: 'Corporate',
    subcategory: 'Event Photography',
    packageType: 'Individual',
    packageName: 'Basic Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '2:00 PM',
    location: 'Bangalore, Karnataka',
    duration: '4 Hours',
    totalAmount: 20000,
    advanceAmount: 20000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '07:15 AM'
  },

  // FOLLOW-UP Bookings - Tomorrow's services
  {
    id: '4',
    bookingId: 'BK004',
    customerName: 'Sneha Reddy',
    customerEmail: 'sneha.reddy@example.com',
    customerPhone: '+91 98765 43213',
    photographerName: 'Karan Chopra',
    category: 'Haldi',
    subcategory: 'Traditional Ceremony',
    packageType: 'Fixed',
    packageName: 'Silver Package',
    bookingDate: getTodayDate(),
    eventDate: getTomorrowDate(),
    eventTime: '11:00 AM',
    location: 'Hyderabad, Telangana',
    duration: '5 Hours',
    totalAmount: 28000,
    advanceAmount: 10000,
    remainingAmount: 18000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-01-25 10:30 AM'
  },
  {
    id: '5',
    bookingId: 'BK005',
    customerName: 'Rohit Malhotra',
    customerEmail: 'rohit.malhotra@example.com',
    customerPhone: '+91 98765 43214',
    photographerName: 'Aditya Kumar',
    category: 'Travel',
    subcategory: 'Adventure Photography',
    packageType: 'Individual',
    packageName: 'Custom Package',
    bookingDate: '2024-02-05',
    eventDate: getTomorrowDate(),
    eventTime: '5:00 AM',
    location: 'Ladakh',
    duration: '3 Days',
    totalAmount: 75000,
    advanceAmount: 25000,
    remainingAmount: 50000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-05 09:00 AM'
  },

  // DELIVERY PENDING - Completed orders awaiting photo delivery
  {
    id: '6',
    bookingId: 'BK006',
    customerName: 'Meera Joshi',
    customerEmail: 'meera.joshi@example.com',
    customerPhone: '+91 98765 43215',
    photographerName: 'Nikhil Desai',
    category: 'Pet Photography',
    subcategory: 'Pet Portrait',
    packageType: 'Fixed',
    packageName: 'Basic Package',
    bookingDate: '2024-02-08',
    eventDate: '2024-02-18',
    eventTime: '3:00 PM',
    location: 'Pune, Maharashtra',
    duration: '2 Hours',
    totalAmount: 8000,
    advanceAmount: 8000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-08 11:00 AM'
  },
  {
    id: '7',
    bookingId: 'BK007',
    customerName: 'Kabir Kapoor',
    customerEmail: 'kabir.kapoor@example.com',
    customerPhone: '+91 98765 43217',
    photographerName: 'Rohan Sharma',
    category: 'Corporate',
    subcategory: 'Product Photography',
    packageType: 'Fixed',
    packageName: 'Premium Package',
    bookingDate: '2024-02-10',
    eventDate: '2024-02-15',
    eventTime: '10:00 AM',
    location: 'Delhi NCR',
    duration: '3 Hours',
    totalAmount: 15000,
    advanceAmount: 15000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-10 08:45 AM'
  },
  {
    id: '8',
    bookingId: 'BK008',
    customerName: 'Neha Gupta',
    customerEmail: 'neha.gupta@example.com',
    customerPhone: '+91 98765 43218',
    photographerName: 'Sanjay Kumar',
    category: 'Birthday',
    subcategory: 'Kids Birthday',
    packageType: 'Fixed',
    packageName: 'Standard Package',
    bookingDate: '2024-02-12',
    eventDate: '2024-02-20',
    eventTime: '4:00 PM',
    location: 'Chennai, Tamil Nadu',
    duration: '3 Hours',
    totalAmount: 12000,
    advanceAmount: 12000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-12 02:30 PM'
  },

  // ADVANCE BOOKINGS - Bookings 2+ days ahead
  {
    id: '9',
    bookingId: 'BK009',
    customerName: 'Ananya Singh',
    customerEmail: 'ananya.singh@example.com',
    customerPhone: '+91 98765 43216',
    photographerName: 'Siddharth Rao',
    category: 'Wedding',
    subcategory: 'Destination Wedding',
    packageType: 'Individual',
    packageName: 'Platinum Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 5);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '9:00 AM',
    location: 'Udaipur, Rajasthan',
    duration: '2 Days',
    totalAmount: 150000,
    advanceAmount: 50000,
    remainingAmount: 100000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-01-30 10:00 AM'
  },
  {
    id: '10',
    bookingId: 'BK010',
    customerName: 'Ravi Shankar',
    customerEmail: 'ravi.shankar@example.com',
    customerPhone: '+91 98765 43219',
    photographerName: 'Manish Patel',
    category: 'Corporate',
    subcategory: 'Conference Photography',
    packageType: 'Fixed',
    packageName: 'Premium Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 7);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '9:00 AM',
    location: 'Mumbai, Maharashtra',
    duration: '8 Hours',
    totalAmount: 45000,
    advanceAmount: 15000,
    remainingAmount: 30000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-01-15 11:30 AM'
  },
  {
    id: '11',
    bookingId: 'BK011',
    customerName: 'Divya Krishnan',
    customerEmail: 'divya.krishnan@example.com',
    customerPhone: '+91 98765 43220',
    photographerName: 'Aarav Mehta',
    category: 'Pre-Wedding',
    subcategory: 'Indoor Studio',
    packageType: 'Fixed',
    packageName: 'Gold Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 10);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '2:00 PM',
    location: 'Bangalore, Karnataka',
    duration: '4 Hours',
    totalAmount: 32000,
    advanceAmount: 32000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-01-20 03:15 PM'
  },
  {
    id: '12',
    bookingId: 'BK012',
    customerName: 'Aryan Desai',
    customerEmail: 'aryan.desai@example.com',
    customerPhone: '+91 98765 43221',
    photographerName: 'Ishaan Singh',
    category: 'Engagement',
    subcategory: 'Ring Ceremony',
    packageType: 'Individual',
    packageName: 'Silver Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 15);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '6:00 PM',
    location: 'Ahmedabad, Gujarat',
    duration: '5 Hours',
    totalAmount: 38000,
    advanceAmount: 15000,
    remainingAmount: 23000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-14 01:00 PM'
  },

  // Additional TODAY bookings (7 more to reach 10)
  {
    id: '13',
    bookingId: 'BK013',
    customerName: 'Kavya Nair',
    customerEmail: 'kavya.nair@example.com',
    customerPhone: '+91 98765 43222',
    photographerName: 'Rohit Jain',
    category: 'Wedding',
    subcategory: 'Mehendi Ceremony',
    packageType: 'Fixed',
    packageName: 'Gold Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '4:00 PM',
    location: 'Kochi, Kerala',
    duration: '6 Hours',
    totalAmount: 42000,
    advanceAmount: 42000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '06:45 AM'
  },
  {
    id: '14',
    bookingId: 'BK014',
    customerName: 'Vikram Sood',
    customerEmail: 'vikram.sood@example.com',
    customerPhone: '+91 98765 43223',
    photographerName: 'Prateek Sharma',
    category: 'Corporate',
    subcategory: 'Annual Meeting',
    packageType: 'Individual',
    packageName: 'Basic Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '11:30 AM',
    location: 'Chandigarh, Punjab',
    duration: '5 Hours',
    totalAmount: 25000,
    advanceAmount: 10000,
    remainingAmount: 15000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '09:20 AM'
  },
  {
    id: '15',
    bookingId: 'BK015',
    customerName: 'Shreya Agarwal',
    customerEmail: 'shreya.agarwal@example.com',
    customerPhone: '+91 98765 43224',
    photographerName: 'Kunal Verma',
    category: 'Pre-Wedding',
    subcategory: 'Beach Shoot',
    packageType: 'Fixed',
    packageName: 'Premium Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '7:00 AM',
    location: 'Goa',
    duration: '8 Hours',
    totalAmount: 55000,
    advanceAmount: 55000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '05:30 AM'
  },
  {
    id: '16',
    bookingId: 'BK016',
    customerName: 'Rohan Gupta',
    customerEmail: 'rohan.gupta@example.com',
    customerPhone: '+91 98765 43225',
    photographerName: 'Siddharth Kumar',
    category: 'Birthday',
    subcategory: 'Anniversary',
    packageType: 'Fixed',
    packageName: 'Silver Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '7:30 PM',
    location: 'Jaipur, Rajasthan',
    duration: '4 Hours',
    totalAmount: 18000,
    advanceAmount: 18000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '12:15 PM'
  },
  {
    id: '17',
    bookingId: 'BK017',
    customerName: 'Isha Patel',
    customerEmail: 'isha.patel@example.com',
    customerPhone: '+91 98765 43226',
    photographerName: 'Arnav Singh',
    category: 'Pet Photography',
    subcategory: 'Pet Fashion',
    packageType: 'Individual',
    packageName: 'Custom Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '3:00 PM',
    location: 'Surat, Gujarat',
    duration: '3 Hours',
    totalAmount: 12000,
    advanceAmount: 5000,
    remainingAmount: 7000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '10:45 AM'
  },
  {
    id: '18',
    bookingId: 'BK018',
    customerName: 'Aditya Khanna',
    customerEmail: 'aditya.khanna@example.com',
    customerPhone: '+91 98765 43227',
    photographerName: 'Vikash Pandey',
    category: 'Travel',
    subcategory: 'Nature Photography',
    packageType: 'Fixed',
    packageName: 'Adventure Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '5:30 AM',
    location: 'Shimla, Himachal Pradesh',
    duration: '10 Hours',
    totalAmount: 65000,
    advanceAmount: 20000,
    remainingAmount: 45000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '04:00 AM'
  },
  {
    id: '19',
    bookingId: 'BK019',
    customerName: 'Deepika Reddy',
    customerEmail: 'deepika.reddy@example.com',
    customerPhone: '+91 98765 43228',
    photographerName: 'Rajesh Kumar',
    category: 'Wedding',
    subcategory: 'Sangam Ceremony',
    packageType: 'Individual',
    packageName: 'Platinum Package',
    bookingDate: getTodayDate(),
    eventDate: getTodayDate(),
    eventTime: '12:00 PM',
    location: 'Vizag, Andhra Pradesh',
    duration: '12 Hours',
    totalAmount: 85000,
    advanceAmount: 30000,
    remainingAmount: 55000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'today',
    deliveryStatus: 'not_applicable',
    createdAt: '11:30 AM'
  },

  // Additional FOLLOW-UP bookings (8 more to reach 10)
  {
    id: '20',
    bookingId: 'BK020',
    customerName: 'Manish Tiwari',
    customerEmail: 'manish.tiwari@example.com',
    customerPhone: '+91 98765 43229',
    photographerName: 'Suresh Nair',
    category: 'Wedding',
    subcategory: 'Reception',
    packageType: 'Fixed',
    packageName: 'Premium Package',
    bookingDate: getTodayDate(),
    eventDate: getTomorrowDate(),
    eventTime: '7:00 PM',
    location: 'Lucknow, Uttar Pradesh',
    duration: '6 Hours',
    totalAmount: 48000,
    advanceAmount: 48000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-10 08:00 AM'
  },
  {
    id: '21',
    bookingId: 'BK021',
    customerName: 'Sunita Iyer',
    customerEmail: 'sunita.iyer@example.com',
    customerPhone: '+91 98765 43230',
    photographerName: 'Gaurav Mehta',
    category: 'Corporate',
    subcategory: 'Product Launch',
    packageType: 'Individual',
    packageName: 'Gold Package',
    bookingDate: '2024-02-12',
    eventDate: getTomorrowDate(),
    eventTime: '10:00 AM',
    location: 'Coimbatore, Tamil Nadu',
    duration: '4 Hours',
    totalAmount: 32000,
    advanceAmount: 32000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-12 02:30 PM'
  },
  {
    id: '22',
    bookingId: 'BK022',
    customerName: 'Akash Joshi',
    customerEmail: 'akash.joshi@example.com',
    customerPhone: '+91 98765 43231',
    photographerName: 'Nitin Sharma',
    category: 'Pre-Wedding',
    subcategory: 'Mountain Shoot',
    packageType: 'Fixed',
    packageName: 'Adventure Package',
    bookingDate: '2024-02-08',
    eventDate: getTomorrowDate(),
    eventTime: '6:00 AM',
    location: 'Manali, Himachal Pradesh',
    duration: '8 Hours',
    totalAmount: 60000,
    advanceAmount: 20000,
    remainingAmount: 40000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-08 11:45 AM'
  },
  {
    id: '23',
    bookingId: 'BK023',
    customerName: 'Pooja Saxena',
    customerEmail: 'pooja.saxena@example.com',
    customerPhone: '+91 98765 43232',
    photographerName: 'Rakesh Singh',
    category: 'Haldi',
    subcategory: 'Traditional Ceremony',
    packageType: 'Individual',
    packageName: 'Silver Package',
    bookingDate: '2024-02-14',
    eventDate: getTomorrowDate(),
    eventTime: '2:00 PM',
    location: 'Bhopal, Madhya Pradesh',
    duration: '5 Hours',
    totalAmount: 30000,
    advanceAmount: 15000,
    remainingAmount: 15000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-14 09:15 AM'
  },
  {
    id: '24',
    bookingId: 'BK024',
    customerName: 'Vishal Agarwal',
    customerEmail: 'vishal.agarwal@example.com',
    customerPhone: '+91 98765 43233',
    photographerName: 'Manoj Kumar',
    category: 'Birthday',
    subcategory: 'Grand Birthday',
    packageType: 'Fixed',
    packageName: 'Premium Package',
    bookingDate: '2024-02-11',
    eventDate: getTomorrowDate(),
    eventTime: '6:00 PM',
    location: 'Indore, Madhya Pradesh',
    duration: '5 Hours',
    totalAmount: 22000,
    advanceAmount: 22000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-11 03:20 PM'
  },
  {
    id: '25',
    bookingId: 'BK025',
    customerName: 'Anjali Verma',
    customerEmail: 'anjali.verma@example.com',
    customerPhone: '+91 98765 43234',
    photographerName: 'Deepak Patel',
    category: 'Pet Photography',
    subcategory: 'Pet Wedding',
    packageType: 'Individual',
    packageName: 'Custom Package',
    bookingDate: '2024-02-13',
    eventDate: getTomorrowDate(),
    eventTime: '11:00 AM',
    location: 'Nagpur, Maharashtra',
    duration: '4 Hours',
    totalAmount: 15000,
    advanceAmount: 15000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-13 01:10 PM'
  },
  {
    id: '26',
    bookingId: 'BK026',
    customerName: 'Sandeep Reddy',
    customerEmail: 'sandeep.reddy@example.com',
    customerPhone: '+91 98765 43235',
    photographerName: 'Kiran Nair',
    category: 'Travel',
    subcategory: 'Wildlife Photography',
    packageType: 'Fixed',
    packageName: 'Safari Package',
    bookingDate: '2024-02-09',
    eventDate: getTomorrowDate(),
    eventTime: '5:00 AM',
    location: 'Jim Corbett, Uttarakhand',
    duration: '12 Hours',
    totalAmount: 80000,
    advanceAmount: 30000,
    remainingAmount: 50000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-09 10:30 AM'
  },
  {
    id: '27',
    bookingId: 'BK027',
    customerName: 'Ritu Sharma',
    customerEmail: 'ritu.sharma@example.com',
    customerPhone: '+91 98765 43236',
    photographerName: 'Ajay Kumar',
    category: 'Engagement',
    subcategory: 'Ring Ceremony',
    packageType: 'Individual',
    packageName: 'Gold Package',
    bookingDate: '2024-02-07',
    eventDate: getTomorrowDate(),
    eventTime: '8:00 PM',
    location: 'Dehradun, Uttarakhand',
    duration: '6 Hours',
    totalAmount: 45000,
    advanceAmount: 45000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-07 04:45 PM'
  },

  // Additional DELIVERY PENDING bookings (7 more to reach 10)
  {
    id: '28',
    bookingId: 'BK028',
    customerName: 'Nikhil Gupta',
    customerEmail: 'nikhil.gupta@example.com',
    customerPhone: '+91 98765 43237',
    photographerName: 'Saurabh Singh',
    category: 'Wedding',
    subcategory: 'Traditional Wedding',
    packageType: 'Fixed',
    packageName: 'Platinum Package',
    bookingDate: '2024-02-05',
    eventDate: '2024-02-10',
    eventTime: '10:00 AM',
    location: 'Agra, Uttar Pradesh',
    duration: '10 Hours',
    totalAmount: 75000,
    advanceAmount: 75000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-05 12:00 PM'
  },
  {
    id: '29',
    bookingId: 'BK029',
    customerName: 'Swati Joshi',
    customerEmail: 'swati.joshi@example.com',
    customerPhone: '+91 98765 43238',
    photographerName: 'Ravi Kumar',
    category: 'Pre-Wedding',
    subcategory: 'Studio Shoot',
    packageType: 'Individual',
    packageName: 'Premium Package',
    bookingDate: '2024-02-03',
    eventDate: '2024-02-08',
    eventTime: '3:00 PM',
    location: 'Vadodara, Gujarat',
    duration: '5 Hours',
    totalAmount: 35000,
    advanceAmount: 35000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-03 08:30 AM'
  },
  {
    id: '30',
    bookingId: 'BK030',
    customerName: 'Harsh Patel',
    customerEmail: 'harsh.patel@example.com',
    customerPhone: '+91 98765 43239',
    photographerName: 'Vikram Singh',
    category: 'Corporate',
    subcategory: 'Trade Show',
    packageType: 'Fixed',
    packageName: 'Standard Package',
    bookingDate: '2024-02-01',
    eventDate: '2024-02-06',
    eventTime: '9:00 AM',
    location: 'Rajkot, Gujarat',
    duration: '6 Hours',
    totalAmount: 28000,
    advanceAmount: 28000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-02-01 06:15 PM'
  },
  {
    id: '31',
    bookingId: 'BK031',
    customerName: 'Kiran Sharma',
    customerEmail: 'kiran.sharma@example.com',
    customerPhone: '+91 98765 43240',
    photographerName: 'Amit Kumar',
    category: 'Birthday',
    subcategory: 'Sweet 16',
    packageType: 'Individual',
    packageName: 'Gold Package',
    bookingDate: '2024-01-30',
    eventDate: '2024-02-04',
    eventTime: '5:00 PM',
    location: 'Jodhpur, Rajasthan',
    duration: '4 Hours',
    totalAmount: 20000,
    advanceAmount: 20000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-01-30 02:45 PM'
  },
  {
    id: '32',
    bookingId: 'BK032',
    customerName: 'Rajesh Kumar',
    customerEmail: 'rajesh.kumar@example.com',
    customerPhone: '+91 98765 43241',
    photographerName: 'Suresh Nair',
    category: 'Pet Photography',
    subcategory: 'Pet Birthday',
    packageType: 'Fixed',
    packageName: 'Basic Package',
    bookingDate: '2024-01-28',
    eventDate: '2024-02-02',
    eventTime: '2:00 PM',
    location: 'Bhubaneswar, Odisha',
    duration: '3 Hours',
    totalAmount: 10000,
    advanceAmount: 10000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-01-28 11:20 AM'
  },
  {
    id: '33',
    bookingId: 'BK033',
    customerName: 'Preeti Agarwal',
    customerEmail: 'preeti.agarwal@example.com',
    customerPhone: '+91 98765 43242',
    photographerName: 'Manoj Sharma',
    category: 'Travel',
    subcategory: 'Heritage Photography',
    packageType: 'Individual',
    packageName: 'Cultural Package',
    bookingDate: '2024-01-25',
    eventDate: '2024-01-30',
    eventTime: '8:00 AM',
    location: 'Hampi, Karnataka',
    duration: '8 Hours',
    totalAmount: 55000,
    advanceAmount: 55000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-01-25 03:30 PM'
  },
  {
    id: '34',
    bookingId: 'BK034',
    customerName: 'Vikash Singh',
    customerEmail: 'vikash.singh@example.com',
    customerPhone: '+91 98765 43243',
    photographerName: 'Raj Kumar',
    category: 'Engagement',
    subcategory: 'Traditional Ceremony',
    packageType: 'Fixed',
    packageName: 'Silver Package',
    bookingDate: '2024-01-22',
    eventDate: '2024-01-27',
    eventTime: '7:00 PM',
    location: 'Patna, Bihar',
    duration: '5 Hours',
    totalAmount: 32000,
    advanceAmount: 32000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'completed',
    serviceStatus: 'completed',
    deliveryStatus: 'pending',
    createdAt: '2024-01-22 09:45 AM'
  },

  // Additional ADVANCE BOOKINGS (7 more to reach 10)
  {
    id: '35',
    bookingId: 'BK035',
    customerName: 'Anita Desai',
    customerEmail: 'anita.desai@example.com',
    customerPhone: '+91 98765 43244',
    photographerName: 'Sunil Kumar',
    category: 'Wedding',
    subcategory: 'Destination Wedding',
    packageType: 'Individual',
    packageName: 'Royal Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 20);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '9:00 AM',
    location: 'Kerala Backwaters',
    duration: '3 Days',
    totalAmount: 200000,
    advanceAmount: 70000,
    remainingAmount: 130000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-15 10:30 AM'
  },
  {
    id: '36',
    bookingId: 'BK036',
    customerName: 'Rohit Malhotra',
    customerEmail: 'rohit.malhotra@example.com',
    customerPhone: '+91 98765 43245',
    photographerName: 'Pankaj Singh',
    category: 'Corporate',
    subcategory: 'Annual Conference',
    packageType: 'Fixed',
    packageName: 'Enterprise Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 25);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '8:00 AM',
    location: 'Gurgaon, Haryana',
    duration: '2 Days',
    totalAmount: 120000,
    advanceAmount: 120000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-14 11:45 AM'
  },
  {
    id: '37',
    bookingId: 'BK037',
    customerName: 'Meera Joshi',
    customerEmail: 'meera.joshi@example.com',
    customerPhone: '+91 98765 43246',
    photographerName: 'Kunal Verma',
    category: 'Pre-Wedding',
    subcategory: 'International Shoot',
    packageType: 'Individual',
    packageName: 'Luxury Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 30);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '10:00 AM',
    location: 'Dubai, UAE',
    duration: '5 Days',
    totalAmount: 350000,
    advanceAmount: 100000,
    remainingAmount: 250000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-13 02:15 PM'
  },
  {
    id: '38',
    bookingId: 'BK038',
    customerName: 'Suresh Kumar',
    customerEmail: 'suresh.kumar@example.com',
    customerPhone: '+91 98765 43247',
    photographerName: 'Amit Patel',
    category: 'Travel',
    subcategory: 'Photography Tour',
    packageType: 'Fixed',
    packageName: 'Expedition Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 35);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '6:00 AM',
    location: 'Ladakh, Jammu & Kashmir',
    duration: '7 Days',
    totalAmount: 180000,
    advanceAmount: 60000,
    remainingAmount: 120000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-12 08:20 AM'
  },
  {
    id: '39',
    bookingId: 'BK039',
    customerName: 'Priya Sharma',
    customerEmail: 'priya.sharma@example.com',
    customerPhone: '+91 98765 43248',
    photographerName: 'Vikram Singh',
    category: 'Wedding',
    subcategory: 'Beach Wedding',
    packageType: 'Individual',
    packageName: 'Ocean Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 40);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '5:00 PM',
    location: 'Andaman Islands',
    duration: '4 Days',
    totalAmount: 280000,
    advanceAmount: 100000,
    remainingAmount: 180000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-11 04:30 PM'
  },
  {
    id: '40',
    bookingId: 'BK040',
    customerName: 'Arjun Patel',
    customerEmail: 'arjun.patel@example.com',
    customerPhone: '+91 98765 43249',
    photographerName: 'Rohit Kumar',
    category: 'Corporate',
    subcategory: 'Product Launch',
    packageType: 'Fixed',
    packageName: 'Launch Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 45);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '2:00 PM',
    location: 'Mumbai, Maharashtra',
    duration: '6 Hours',
    totalAmount: 85000,
    advanceAmount: 85000,
    remainingAmount: 0,
    paymentStatus: 'paid',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-10 12:00 PM'
  },
  {
    id: '41',
    bookingId: 'BK041',
    customerName: 'Sneha Reddy',
    customerEmail: 'sneha.reddy@example.com',
    customerPhone: '+91 98765 43250',
    photographerName: 'Kiran Singh',
    category: 'Pre-Wedding',
    subcategory: 'Mountain Adventure',
    packageType: 'Individual',
    packageName: 'Summit Package',
    bookingDate: getTodayDate(),
    eventDate: (() => {
      const futureDate = new Date();
      futureDate.setDate(futureDate.getDate() + 50);
      return futureDate.toISOString().split('T')[0];
    })(),
    eventTime: '4:00 AM',
    location: 'Leh, Ladakh',
    duration: '10 Days',
    totalAmount: 420000,
    advanceAmount: 150000,
    remainingAmount: 270000,
    paymentStatus: 'partial',
    bookingStatus: 'confirmed',
    serviceStatus: 'upcoming',
    deliveryStatus: 'not_applicable',
    createdAt: '2024-02-09 06:45 AM'
  },
];

export default function BookingsPage() {
  const [bookings, setBookings] = useState<Booking[]>(initialBookings);

  return (
    <div className="min-h-screen bg-gray-50">
      <Sidebar activeTab="bookings" onTabChange={(tab) => window.location.href = `/${tab}`} />
      <div className="pt-16 transition-all duration-300 p-4 md:p-8">
        <BookingManagement bookings={bookings} setBookings={setBookings} />
      </div>
    </div>
  );
}

